# Author:  Joe Harrison
# This is a GitHub Actions workflow that uses Terraform to deploy a vSphere K8S cluster using Rocky Linux VMs. 
# It will generate a main.tf file based on user input, in the root of the repository and then apply the Terraform configuration to create the cluster. 
# If the Terraform apply fails, it will initiate a cleanup by destroying the resources created.

# Name of the workflow
name: 'vSphere K8S CD'
# Define environment variables
env:
  # vSphere password used for authentication
  TF_VAR_vsphere_password: ${{ secrets.VSPHERE_PASSWORD }}
  # SSH password used for authentication
  TF_VAR_ssh_password: ${{ secrets.SSH_PASSWORD }}  

# Define the events that trigger the workflow
on:
  # Trigger the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      vsphere_server:
        description: 'Enter the vSphere Server IP, User, Datacenter, Cluster to deploy the K8S on, separated by commas, i.e. "192.168.1.100,user@domain.local,DATACENTER1,CLUSTER4"'
        required: true
      vsphere_stack:
        description: 'Enter stack shorthand name and folder path to deploy to i.e."pe,PATH/TO/K8S Cluster" this is for a Production Environment into a K8S Cluster folder'
        required: true
      vsphere_datastore:
        description: 'Enter the vSphere datastore to deploy the k8s on'
        required: true
      vsphere_network:
        description: 'Enter the vSphere port group to connect the k8s to'
        required: true
      deployment_ip:
        description: 'Enter ip address for the admin host 10.0.10.150, node ips follow this sequentially'
        required: true        
      deployment_cidr:
        description: 'Enter network subnet cidr i.e. /22 or /24 with "/"'
        required: true
      deployment_gateway:
        description: 'Enter network gateway cidr i.e. 10.0.10.1'
        required: true        
      number_of_nodes:
        description: 'Enter the total number of nodes to deploy (masters and workers combined)'
        required: true        
      deployment_cpu:
        description: 'Enter the number of CPUs to allocate to the k8s'
        required: true
        type: choice
        options:
        - '4'
        - '8'
        - '16'
        - '32'
      deployment_ram:
        description: 'Enter the amount of RAM to allocate to the VM in MB'
        required: true
        type: choice
        options:
        - '8192'
        - '16384'
        - '32768'
        - '65536'

# Define permissions for this workflow
permissions:
  contents: read

# Define jobs in this workflow  
jobs:
  # Define a job for main.tf file actions
  generate-main-tf:
    name: 'Terraform vSphere K8S main.tf Generation'
    runs-on: [self-hosted, devops]
    environment: production

    steps:
      # Checkout the repository to the GitHub Actions runner 
      - name: Checkout
        uses: actions/checkout@v4  

      # If main.tf does not exist, we generate a new one using user input
      - name: Check if main.tf exists
        run: |
          if [ -f "main.tf" ]; then
            echo "main.tf already exists, skipping file generation."
            echo "file_exists=true" >> $GITHUB_ENV      
          else
            echo "main.tf does not exist, continuing with file generation."
            echo "file_exists=false" >> $GITHUB_ENV
          fi
        id: check-main-tf
      
      - name: Generate main.tf with user input
        if: env.file_exists == 'false'
        run: |
          # Using the Internal Field Separator (IFS) variable, parse the input strings into individual variables
          IFS=',' read -r vsphere_server vsphere_user vsphere_datacenter vsphere_cluster <<< "${{ github.event.inputs.vsphere_server }}"
          cat > main.tf << EOF
          # Variables to be populated by GitHub Secrets at runtime
          # vCenter Password
          variable "vsphere_password" {}
          
          # Define the required version of Terraform and the required vSphere and AWS provider version
          terraform {
            required_version = ">= 1.5.0"

            required_providers {
              vsphere = {
                source = "hashicorp/vsphere"
                version = "2.4.1"
              }
              
            }
            
          }
          
          # Connection to vSphere environment
          provider "vsphere" {
            user                  = "$vsphere_user"
            password              = var.vsphere_password
            vsphere_server        = "$vsphere_server"
            allow_unverified_ssl  = true
          }
          
          # Define the module source and its location
          module "vsphere-k8s" {
            source = "./modules/vsphere-k8s" 
          
            # Define vSphere Information 
            vsphere_config = {
              vcenter_server = "$vsphere_server"
              user           = "$vsphere_user"
              datacenter     = "$vsphere_datacenter"
              cluster        = "$vsphere_cluster"
              datastore      = "<vsphere_datastore>"
              vapp           = "k8s"
              vm_network     = "<vsphere_network>"
              vm_folder      = "<vm_folder>"
            }
          
            # Define Global K8S Information 
            k8s-global = {
              username       = "k8sadmin"
              timezone       = "Europe/London"
              run_kubespray  = "yes"
              kube_version   = "v1.26.0"
              private_key    = "id_rsa-k8s-on-vmware"
              public_key     = "id_rsa-k8s-on-vmware.pub"
            }
            
            # Define Admin Node Information 
            k8s-admin-node = {
              hostname            = "<vsphere_stack>-k8s-admin"
              num_cpus            = "8"
              memory              = "16384"
              disk_size           = "200"
              mgmt_use_dhcp       = "no"
              mgmt_interface_name = "ens192"
              mgmt_subnet         = "<deployment_subnet_cidr>"
              mgmt_ip             = "<deployment_ip><deployment_subnet_cidr>"
              mgmt_gateway        = "<deployment_gateway>"
              mgmt_dns_servers    = "1.1.1.1,1.0.0.1"
              template            = "ROCKY-9_3-PKR-V1"
            }  
            
            # Define Node Information 
            k8s-nodes = {
              hostname                = "<vsphere_stack>-k8s-"
              number_of_nodes         = "<node_count>"
              mgmt_m_nodes_total      = "<master_count>"	
              num_cpus                = "<deployment_cpu>"
              memory                  = "<deployment_ram>"
              disk_size               = "200"
              template                = "ROCKY-9_3-PKR-V1"
              mgmt_use_dhcp           = "no"
              mgmt_interface_name     = "ens192"
              mgmt_subnet             = "<deployment_subnet_cidr>"
              mgmt_subnet_full        = "<deployment_subnet_full>"
              mgmt_startip            = "<deployment_start_ip>"
              mgmt_startip_lastoct    = "<deployment_last_oct>"
              mgmt_gateway            = "<deployment_gateway>"
              mgmt_dns_servers        = "1.1.1.1,1.0.0.1"
              mgmt_node_ips           = "<mgmt_node_ips>"
            }
          }
          
          output "k8s-output" {
            value = module.vsphere-k8s
          }  
          EOF
          
          # Replace the placeholders with the actual input values
          sed -i "s|<vsphere_datastore>|${{ github.event.inputs.vsphere_datastore }}|g" main.tf
          sed -i "s|<vsphere_network>|${{ github.event.inputs.vsphere_network }}|g" main.tf
          
          IFS=',' read -ra VSPHERE_STACK_INFO <<< "${{ github.event.inputs.vsphere_stack }}"
          sed -i "s|<vsphere_stack>|${VSPHERE_STACK_INFO[0]}|g" main.tf
          sed -i "s|<vm_folder>|${VSPHERE_STACK_INFO[1]}|g" main.tf
          sed -i "s|<deployment_subnet_cidr>|${{ github.event.inputs.deployment_cidr }}|g" main.tf
          sed -i "s|<deployment_ip>|${{ github.event.inputs.deployment_ip }}|g" main.tf
          sed -i "s|<deployment_gateway>|${{ github.event.inputs.deployment_gateway }}|g" main.tf
          sed -i "s|<node_count>|${{ github.event.inputs.number_of_nodes }}|g" main.tf

          number_of_nodes="${{ github.event.inputs.number_of_nodes }}"
          if (( number_of_nodes <= 10 )); then
            master_nodes=3
          elif (( number_of_nodes > 10 )); then
            master_nodes=5
          fi
          
          sed -i "s|<master_count>|$master_nodes|g" main.tf
          sed -i "s|<deployment_cpu>|${{ github.event.inputs.deployment_cpu }}|g" main.tf
          sed -i "s|<deployment_ram>|${{ github.event.inputs.deployment_ram }}|g" main.tf  
          
          # Calculate the full subnet address
          gateway="${{ github.event.inputs.deployment_gateway }}"
          cidr="${{ github.event.inputs.deployment_cidr }}"
          IFS='.' read -r -a gateway_octets <<< "$gateway"
          IFS='/' read -r -a cidr_parts <<< "$cidr"
          subnet_mask=$(( 0xFFFFFFFF << (32 - ${cidr_parts[1]}) ))
          subnet_octets=()
          for i in "${!gateway_octets[@]}"; do
            subnet_octet=$(( gateway_octets[i] & (subnet_mask >> (8 * (3 - i))) ))
            subnet_octets+=("$subnet_octet")
          done
          subnet_full="${subnet_octets[0]}.${subnet_octets[1]}.${subnet_octets[2]}.${subnet_octets[3]}/${cidr_parts[1]}"
          sed -i "s|<deployment_subnet_full>|$subnet_full|g" main.tf  
        
          # Calculate the starting IP address
          ip_address="${{ github.event.inputs.deployment_ip }}"
          incremented_ip=$(printf "%d.%d.%d.%d" $(echo $ip_address | tr '.' ' ' | awk '{print $1+0,$2+0,$3+0,$4+1}'))
          sed -i "s|<deployment_start_ip>|$incremented_ip|g" main.tf  
                    
          # Calculate the last octet of the starting IP address
          last_octet="${incremented_ip##*.}"  
          sed -i "s|<deployment_last_oct>|$last_octet|g" main.tf       

          # Calculate node ips
          nodes="${{ github.event.inputs.number_of_nodes }}"
          ip_address="${{ github.event.inputs.deployment_ip }}"
          ip_list=""
          for ((i = 1; i <= nodes; i++)); do
            ip_list+="${ip_address%.*}.$((${ip_address##*.} + i)),"
          done
          ip_list="${ip_list%,}" # Remove the trailing comma
          sed -i "s|<mgmt_node_ips>|$ip_list|g" main.tf  

          # Print the generated main.tf
          cat main.tf
      
      # If a new main.tf file was created, commit and push it to the repository
      - name: Commit and push main.tf
        if: steps.check-main-tf.outputs.file_exists == 'false'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add main.tf
          git commit -m "Add generated main.tf"
          git push 

  # Define a job for Terraform actions          
  terraform-vsphere-k8s-pipeline:
    name: 'Terraform K8S Pipeline'
    needs: generate-main-tf
    runs-on: [self-hosted, devops]
    environment: production

    steps:   
    # Checkout the repository to the GitHub Actions runner 
    - name: Checkout
      uses: actions/checkout@v4

    # Fetch the latest commit  
    - name: Fetch the latest commit
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/* --depth=1
        LATEST_COMMIT=$(git rev-parse origin/${GITHUB_REF##*/})
        git checkout $LATEST_COMMIT 
              
    # Setup Node.js environment with a specific version
    - name: Node Setup
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    # Setup Terraform CLI on the runner
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    # Initialise your Terraform working directory
    - name: Terraform Init
      run: terraform init

    # Generate an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan
    
    # Apply the changes required to reach the desired state of the configuration
    - name: Terraform Apply
      id: apply    
      continue-on-error: true
      run: terraform apply -auto-approve

    # Check if Terraform Apply failed and set an output variable
    - name: Check Terraform Apply Outcome
      id: check
      run: echo "apply_failed=${{ steps.apply.outcome == 'failure' }}" >> $GITHUB_ENV

    # Destroy if Terraform Apply failed
    - name: Terraform Apply Failure Handler
      if: env.apply_failed == 'true'
      id: failure-handler
      run: |
        echo "Terraform Apply failed. Initiating cleanup..."
        terraform destroy -auto-approve
        echo "cleanup_done=true" >> $GITHUB_ENV          

    # If SSH keys exist in the root of the repo
    - name: Check SSH Key Existance
      run: |
        if [ -f "id_rsa-k8s-on-vmware" ]; then
          echo "keys already exists, skipping commit."
          echo "keys_exist=true" >> $GITHUB_ENV
        else
          echo "keys do not exist, continuing with commit."
          echo "keys_exist=false" >> $GITHUB_ENV
        fi
      id: check-keys
      
    # If a new SSH key files were created, commit and push it to the repository
    - name: Commit and Push SSH Keys
      if: env.keys_exist == 'true' && env.steps.cleanup_done != 'true'
      run: |
        # Set Git configurations
        git config --global user.name "GitHub Actions" || true
        git config --global user.email "github-actions@users.noreply.github.com" || true

        # Add SSH key files
        git add id_rsa-k8s-on-vmware id_rsa-k8s-on-vmware.pub

        # Check if there are changes to commit
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit. Skipping commit and push."
        else
          # Commit and push changes
          git commit -m "commit deployment SSH keys"
          git push --force
        fi        